-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Ingredients
    = Ingredients


type Ingredients_aggregate
    = Ingredients_aggregate


type Ingredients_aggregate_fields
    = Ingredients_aggregate_fields


type Ingredients_avg_fields
    = Ingredients_avg_fields


type Ingredients_max_fields
    = Ingredients_max_fields


type Ingredients_min_fields
    = Ingredients_min_fields


type Ingredients_mutation_response
    = Ingredients_mutation_response


type Ingredients_stddev_fields
    = Ingredients_stddev_fields


type Ingredients_stddev_pop_fields
    = Ingredients_stddev_pop_fields


type Ingredients_stddev_samp_fields
    = Ingredients_stddev_samp_fields


type Ingredients_sum_fields
    = Ingredients_sum_fields


type Ingredients_var_pop_fields
    = Ingredients_var_pop_fields


type Ingredients_var_samp_fields
    = Ingredients_var_samp_fields


type Ingredients_variance_fields
    = Ingredients_variance_fields


type Recipes
    = Recipes


type Recipes_aggregate
    = Recipes_aggregate


type Recipes_aggregate_fields
    = Recipes_aggregate_fields


type Recipes_avg_fields
    = Recipes_avg_fields


type Recipes_max_fields
    = Recipes_max_fields


type Recipes_min_fields
    = Recipes_min_fields


type Recipes_mutation_response
    = Recipes_mutation_response


type Recipes_stddev_fields
    = Recipes_stddev_fields


type Recipes_stddev_pop_fields
    = Recipes_stddev_pop_fields


type Recipes_stddev_samp_fields
    = Recipes_stddev_samp_fields


type Recipes_sum_fields
    = Recipes_sum_fields


type Recipes_var_pop_fields
    = Recipes_var_pop_fields


type Recipes_var_samp_fields
    = Recipes_var_samp_fields


type Recipes_variance_fields
    = Recipes_variance_fields
