-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Ingredients_sum_fields exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


amount : SelectionSet (Maybe Api.ScalarCodecs.Numeric) Api.Object.Ingredients_sum_fields
amount =
    Object.selectionForField "(Maybe ScalarCodecs.Numeric)" "amount" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecNumeric |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe Int) Api.Object.Ingredients_sum_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


recipe : SelectionSet (Maybe Int) Api.Object.Ingredients_sum_fields
recipe =
    Object.selectionForField "(Maybe Int)" "recipe" [] (Decode.int |> Decode.nullable)
