-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Ingredients exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


additional_information : SelectionSet String Api.Object.Ingredients
additional_information =
    Object.selectionForField "String" "additional_information" [] Decode.string


amount : SelectionSet Api.ScalarCodecs.Numeric Api.Object.Ingredients
amount =
    Object.selectionForField "ScalarCodecs.Numeric" "amount" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecNumeric |> .decoder)


amount_unit : SelectionSet String Api.Object.Ingredients
amount_unit =
    Object.selectionForField "String" "amount_unit" [] Decode.string


id : SelectionSet Int Api.Object.Ingredients
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Api.Object.Ingredients
name =
    Object.selectionForField "String" "name" [] Decode.string


recipe : SelectionSet Int Api.Object.Ingredients
recipe =
    Object.selectionForField "Int" "recipe" [] Decode.int


{-| An object relationship
-}
recipeByRecipe :
    SelectionSet decodesTo Api.Object.Recipes
    -> SelectionSet decodesTo Api.Object.Ingredients
recipeByRecipe object_ =
    Object.selectionForCompositeField "recipeByRecipe" [] object_ identity
