-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Ingredients_min_fields exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


additional_information : SelectionSet (Maybe String) Api.Object.Ingredients_min_fields
additional_information =
    Object.selectionForField "(Maybe String)" "additional_information" [] (Decode.string |> Decode.nullable)


amount : SelectionSet (Maybe Api.ScalarCodecs.Numeric) Api.Object.Ingredients_min_fields
amount =
    Object.selectionForField "(Maybe ScalarCodecs.Numeric)" "amount" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecNumeric |> .decoder |> Decode.nullable)


amount_unit : SelectionSet (Maybe String) Api.Object.Ingredients_min_fields
amount_unit =
    Object.selectionForField "(Maybe String)" "amount_unit" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe Int) Api.Object.Ingredients_min_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


name : SelectionSet (Maybe String) Api.Object.Ingredients_min_fields
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


recipe : SelectionSet (Maybe Int) Api.Object.Ingredients_min_fields
recipe =
    Object.selectionForField "(Maybe Int)" "recipe" [] (Decode.int |> Decode.nullable)
