-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Recipes_min_fields exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


cover_image_url : SelectionSet (Maybe String) Api.Object.Recipes_min_fields
cover_image_url =
    Object.selectionForField "(Maybe String)" "cover_image_url" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Api.Object.Recipes_min_fields
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe Int) Api.Object.Recipes_min_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


instructions : SelectionSet (Maybe String) Api.Object.Recipes_min_fields
instructions =
    Object.selectionForField "(Maybe String)" "instructions" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) Api.Object.Recipes_min_fields
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
