-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Recipes.Object.Ingredients exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Recipes.InputObject
import Recipes.Interface
import Recipes.Object
import Recipes.Scalar
import Recipes.ScalarCodecs
import Recipes.Union


additional_information : SelectionSet String Recipes.Object.Ingredients
additional_information =
    Object.selectionForField "String" "additional_information" [] Decode.string


amount : SelectionSet Recipes.ScalarCodecs.Numeric Recipes.Object.Ingredients
amount =
    Object.selectionForField "ScalarCodecs.Numeric" "amount" [] (Recipes.ScalarCodecs.codecs |> Recipes.Scalar.unwrapCodecs |> .codecNumeric |> .decoder)


amount_unit : SelectionSet String Recipes.Object.Ingredients
amount_unit =
    Object.selectionForField "String" "amount_unit" [] Decode.string


id : SelectionSet Int Recipes.Object.Ingredients
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Recipes.Object.Ingredients
name =
    Object.selectionForField "String" "name" [] Decode.string


recipe : SelectionSet Int Recipes.Object.Ingredients
recipe =
    Object.selectionForField "Int" "recipe" [] Decode.int


{-| An object relationship
-}
recipeByRecipe :
    SelectionSet decodesTo Recipes.Object.Recipes
    -> SelectionSet decodesTo Recipes.Object.Ingredients
recipeByRecipe object_ =
    Object.selectionForCompositeField "recipeByRecipe" [] object_ identity
