-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Recipes.Object.Recipes_max_fields exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Recipes.InputObject
import Recipes.Interface
import Recipes.Object
import Recipes.Scalar
import Recipes.ScalarCodecs
import Recipes.Union


cover_image_url : SelectionSet (Maybe String) Recipes.Object.Recipes_max_fields
cover_image_url =
    Object.selectionForField "(Maybe String)" "cover_image_url" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Recipes.Object.Recipes_max_fields
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe Int) Recipes.Object.Recipes_max_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


instructions : SelectionSet (Maybe String) Recipes.Object.Recipes_max_fields
instructions =
    Object.selectionForField "(Maybe String)" "instructions" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) Recipes.Object.Recipes_max_fields
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
