-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Recipes.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Recipes.Scalar exposing (defaultCodecs)


type alias Id =
    Recipes.Scalar.Id


type alias Numeric =
    Recipes.Scalar.Numeric


codecs : Recipes.Scalar.Codecs Id Numeric
codecs =
    Recipes.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecNumeric = defaultCodecs.codecNumeric
        }
