-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Ingredients_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "ingredients"

  - Ingredients\_pkey - unique or primary key constraint

-}
type Ingredients_constraint
    = Ingredients_pkey


list : List Ingredients_constraint
list =
    [ Ingredients_pkey ]


decoder : Decoder Ingredients_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ingredients_pkey" ->
                        Decode.succeed Ingredients_pkey

                    _ ->
                        Decode.fail ("Invalid Ingredients_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Ingredients_constraint -> String
toString enum =
    case enum of
        Ingredients_pkey ->
            "ingredients_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Ingredients_constraint
fromString enumString =
    case enumString of
        "ingredients_pkey" ->
            Just Ingredients_pkey

        _ ->
            Nothing
