-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Recipes_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "recipes"

  - Recipes\_pkey - unique or primary key constraint

-}
type Recipes_constraint
    = Recipes_pkey


list : List Recipes_constraint
list =
    [ Recipes_pkey ]


decoder : Decoder Recipes_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "recipes_pkey" ->
                        Decode.succeed Recipes_pkey

                    _ ->
                        Decode.fail ("Invalid Recipes_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Recipes_constraint -> String
toString enum =
    case enum of
        Recipes_pkey ->
            "recipes_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Recipes_constraint
fromString enumString =
    case enumString of
        "recipes_pkey" ->
            Just Recipes_pkey

        _ ->
            Nothing
